[package]
name = "zygisk-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
v2 = []
v3 = []
v4 = []
default = ["v2"]

[dependencies]
typed-jni = { version = "^1.1" }
libc = "^0.2"
rustix = "^1.1"
